// PART 1: SCRIPTURE STREAM (50 REFS)
const victoryRefs = [
    "Joshua+1:9", "Isaiah+41:10", "Deuteronomy+28:12", "Psalm+18:2", "Jeremiah+29:11", 
    "Romans+8:37", "2Corinthians+2:14", "Philippians+4:19", "Psalm+23:1", "Isaiah+54:17",
    "Psalm+27:1", "Micah+7:8", "Exodus+14:14", "Deuteronomy+20:4", "Psalm+44:5",
    "Psalm+60:12", "Proverbs+21:31", "1Corinthians+15:57", "2Corinthians+10:4", "1John+5:4",
    "Revelation+12:11", "Psalm+118:15", "Isaiah+40:31", "Romans+8:31", "Zechariah+4:6",
    "Psalm+34:17", "Psalm+37:4", "Genesis+50:20", "Matthew+19:26", "Mark+9:23",
    "Luke+1:37", "John+16:33", "Acts+1:8", "Ephesians+3:20", "Colossians+2:15",
    "2Timothy+1:7", "Hebrews+11:1", "James+4:7", "1Peter+5:10", "Psalm+91:1",
    "Psalm+121:1", "Isaiah+43:19", "Joel+2:25", "Amos+9:13", "Malachi+3:10",
    "Habakkuk+3:19", "Zephaniah+3:17", "Psalm+138:8", "Romans+16:20", "2Thessalonians+3:3"
];

// PART 2: ANCIENT TESTIMONIES (30 TOTAL)
const testimonies = [
    { title: "The Red Sea Bypass", body: "You’re backed against a wall with an army behind you and an ocean in front of you. Don't panic. The same God who made the water is about to make it a dry highway. Your 'no-way-out' situation is just a stage for a miracle that defies physics." },
    { title: "The Jericho Sound-Wave", body: "You've been circling the same problem for months. The walls look thick, but they’re vibration-sensitive. One shout of praise is about to trigger a structural collapse of every barrier." },
    { title: "The Shadrach Fire-Walk", body: "The fire only burned the ropes that tied your hands. You aren't just surviving the furnace; you’re walking in it with a Fourth Man. You're coming out without even the smell of smoke." },
    { title: "The Daniel Lion-Vibe", body: "The predators are hungry, but God just locked their jaws. Your integrity has silenced the ones trying to eat your future. Peace in the pit is your ultimate flex." },
    { title: "The Lazarus Resurrection", body: "No situation is too dead for God to bring back to life. Lazarus was dead four days, yet the call went forth. Your dead dreams are being revived." },
    { title: "The Joseph Setup", body: "The pit was preparing him for the palace. What looks like a setback in your life is actually a divine setup for a manifestation of power." },
    { title: "The Esther Royal-Risk", body: "You weren't lucky to get that position; you were drafted for this exact crisis. Step into the room with confidence—the King’s heart is leaning toward you." },
    { title: "The Widow’s Oil-Flow", body: "You’re down to your last drop. Start pouring anyway. As long as you provide the empty jars, God will provide the overflow." },
    { title: "The Paul & Silas Jail-Jam", body: "It’s midnight, feet in chains. Start singing. Your praise is triggering an earthquake that pops every lock in the building. You're taking the jailer with you." },
    { title: "The Hezekiah Extension", body: "The report said it was over. You turned your face to the wall. God just added 15 years to your clock and moved the sun backward to prove it." },
    { title: "The Gideon Underdog", body: "You feel outnumbered. God cut your team to 300 so the world knows this was a Holy Spirit takeover." },
    { title: "The Jabez Boundary-Shift", body: "You were born into 'Pain,' but you’re praying for 'Expansion.' God just hit the 'Approve' button on your territory." },
    { title: "The Mephibosheth Table-Invite", body: "You felt forgotten in Lo-debar. Suddenly, the King remembers the covenant. You’re moving to the Palace table today." },
    { title: "The Woman’s Faith-Touch", body: "Twelve years of losing money and hope, but one second of touching the hem of His garment fixed it all." },
    { title: "The Bartimaeus Shout", body: "Everyone told you to be quiet. Shout louder. The Son of David just stopped because He heard your persistence." },
    { title: "The Centurion Word-Order", body: "You don't need a physical visit; you just need a Word. The healing is happening 'at this very hour' miles away." },
    { title: "The Cana Upgrade", body: "The party ran out of wine. God turned tap water into top-shelf vintage. Your 'finish' was just a setup for an upgrade." },
    { title: "The Pentecostal Surge", body: "You’ve been waiting. Suddenly, the sound of a rushing wind filled the house. Your influence is going global." },
    { title: "The Ruthless Loyalty", body: "You lost everything in Moab, but you’re following the Promise. You’re 'gleaning' today, but you’ll own the whole estate tomorrow." },
    { title: "The Rahab Red-Cord", body: "Your past was 'shady,' but your future is 'pivotal.' While the walls fall, your house is a sanctuary." },
    { title: "The Resurrection Morning", body: "The 'end' was just a three-day pause. You aren't just back; you’re back with the keys to death and hell." },
    { title: "The Elisha Double-Portion", body: "You didn't just watch the mentor; you served the mantle. You’re now operating with twice the power." },
    { title: "The Valley of Berakah", body: "Three armies surrounded you. By the time you finished singing, the enemies had taken each other out. Collect the loot." },
    { title: "The Solomon Dream-Gift", body: "God asked what you wanted. You asked for wisdom. He’s giving you the wisdom AND the wealth you didn't even mention." },
    { title: "The Naaman Dip", body: "You wanted a ceremony, but God gave you a muddy river. Swallow your pride and dip. Obedience is the medicine." },
    { title: "The Tabitha Wake-Up", body: "The community was weeping over your 'end.' But the Word went forth: 'Arise.' Your work wasn't finished." },
    { title: "The Elijah Fire-Download", body: "The atmosphere is dry and the mockers are loud. Keep building the altar. When the fire falls, it will lick up the water in the trenches." },
    { title: "The Jailer’s Household Shift", body: "One man’s breakthrough just saved an entire family. Your personal victory is a generational rescue mission." },
    { title: "The Abrahamic Endurance", body: "Abraham believed even when it contradicted his natural eyes. Your season of waiting has not been wasted time; it has been the perfection of your trust." },
    { title: "The Davidic Cave", body: "Every battle you have fought in secret has qualified you for the public victory I am releasing now." }
];

// PART 3: THE FINAL DECREES (120 TOTAL)
const finalDecrees = [
    "I am officially hacking every system that tried to lock you out of your inheritance.",
    "Your credit score in the spirit is 'Infinite'; stop acting like you’re broke.",
    "I am deleting the 'Wait' status on your paperwork; your approval is moving to the top.",
    "Your 'overlooked' era is over; your 'undeniable' era is starting right now.",
    "I am re-routing the supply lines; what was stuck in logistics is arriving today.",
    "The 'shady' characters in your life are being exposed and evicted from your circle.",
    "I am giving you high-level clearance to walk into rooms you used to be intimidated by.",
    "Your side-hustle is about to become your main-stream; get ready for expansion.",
    "I am upgrading your internal OS; no more bugging out over old anxieties.",
    "Your 'impulse to fail' is being overwritten by a 'drive to dominate'.",
    "The legal battle is shifting in your favor; the Judge of Heaven hammered a 'Dismissed'.",
    "I am putting a 'Do Not Touch' sign on your family in the spiritual realm.",
    "Your resume is being highlighted by the Holy Spirit in the hands of the right CEO.",
    "Every generational curse that slowed down your parents is officially canceled for you.",
    "I am putting the 'Right Person' in the 'Right Place' at the 'Right Time' for your breakthrough.",
    "The 'invisible' ceiling over your income is being shattered by a prophetic hammer.",
    "I am giving you a spirit of 'Mastery'; you won't just participate, you will lead.",
    "I am authorizing a 'New Beginning' stamp on your current project.",
    "I am putting the 'Midas Touch' on your hands; whatever you build, thrives.",
    "I am authorizing a 'Surge' in your spiritual authority; demons now recognize your name.",
    "I am giving you 'First-Class' favor on a 'Coach' budget until the upgrade hits.",
    "I am putting 'Holy Spirit Fire' on your tongue; your words will burn through lies.",
    "I am opening the 'Floodgates' of joy; your laughter will return in a torrent.",
    "I am giving you 'Keys' to properties you haven't even toured yet.",
    "I am putting 'God-Speed' on your recovery; you will finish ahead of schedule.",
    "I am giving you 'Dominion' over your day; stop letting the clock rule you.",
    "Your aura is shifting; when you walk in, the atmosphere of the room has to align with you.",
    "I am removing the 'blind spots' in your business strategy; see the money-holes before they happen.",
    "The toxic debt is being dissolved through supernatural financial strategy.",
    "I am giving you the strength to say 'No' to good things so you can say 'Yes' to the Great Thing.",
    "Your social media reach is being expanded to find the people who actually need your light.",
    "I am putting a hedge of protection around your mental health today; no entry for dark thoughts.",
    "Your physical body is coming into alignment with divine health; every cell, wake up.",
    "I am giving you the courage to delete the contacts that are weighing down your destiny.",
    "I am restoring your sleep cycles; no more midnight panic, only midnight revelation.",
    "Your 'limp' is becoming your 'leap'; the very thing that hurt you is now your fuel.",
    "The shadow of your past is being swallowed up by the brilliance of your future.",
    "Your voice is being amplified; what you say in secret will manifest on the housetops.",
    "I am providing the 'Seed' for the 'Sower'; your investment capacity is tripling.",
    "The 'ghosts' of your former mistakes are being permanently exorcised from your mind.",
    "I am bringing you into 'Deep Water' where the big fish are; leave the shore.",
    "Your 'imposter syndrome' is being replaced by 'Sonship/Daughtership' authority.",
    "I am putting a 'Prophetic Shield' around your creativity; no more stolen ideas.",
    "Your season of 'Begging' is over; your season of 'Bequesting' is here.",
    "I am opening a vault of ancient wisdom and handing you the combination.",
    "Your 'stuck' wheels are finally finding traction on the high-speed rail of destiny.",
    "I am giving you a 'New Song' that will break the depression of everyone who hears it.",
    "Your 'slow-burn' is turning into a 'flash-over'; the fire is spreading fast.",
    "The 'locked' chapter of your life is being pried open with the Key of David.",
    "I am giving you a 'Seat at the Table' you didn't even know was being set.",
    "Your 'broken heart' is being replaced by a 'lion heart'; fierce and compassionate.",
    "I am deleting the 'Failure' tags from your spiritual metadata.",
    "Your 'dry bones' aren't just rattling; they are standing up and forming an army.",
    "I am giving you 'Infrared Vision' to see through the lies of the enemy.",
    "Your 'heavy lifting' days are over; I am the Wind beneath your wings.",
    "Your 'waiting' was actually 'incubating'; the thing inside you is now ready to be born.",
    "Your 'shame' is being exchanged for 'double honor' in the sight of everyone.",
    "Your 'lonely' season was actually a 'hidden' season; I was keeping you for Myself.",
    "Your 'small' beginnings are being multiplied into 'Global' impacts.",
    "I am giving you a 'New Name' in the Spirit; walk like the royalty I called you.",
    "The 'famine' in your field is being canceled by a 'downpour' of grace.",
    "I am putting 'Iron' in your spine; you will stand tall against the wind of the world.",
    "Your 'exhaustion' is being met by My 'Exuberance'; receive fresh oil.",
    "I am giving you the 'Victory' before you even see the 'Battle'.",
    "Your 'broken' pieces are being fused together into a 'stunning' mosaic.",
    "I am authorizing a 'New Level' of peace that makes no sense to the world.",
    "Your 'manifestation' isn't just coming; it is already 'Manifesting' as you read this.",
    "Your 'enemies' are being made your 'footstool'; use them to step higher.",
    "Your 'quiet' confidence is more powerful than their 'loud' arrogance.",
    "I am giving you 'X-Ray' discernment to see people's true intentions.",
    "Your 'breakthrough' is a 'Break-Out' from every cage you've ever known.",
    "I am putting 'Royal Robes' on you; leave the rags of the 'Old Self' behind.",
    "Your 'destiny' is calling your name; answer the phone with a 'Yes'.",
    "I am giving you 'Dominion' over your day; stop letting the clock rule you.",
    "The pressure you feel is not for your destruction; it is the birth pangs of breakthrough.",
    "I am giving you the tools today for the territory you will occupy tomorrow.",
    "I am turning your mourning into dancing; clothing you with joy.",
    "I am the Alpha and the Omega; I have already seen the end, and you win.",
    "Write the vision and make it plain; wait for it, for it will certainly come.",
    "He who began a good work in you will carry it on to completion.",
    "I am your Advocate in the courts of heaven; speaking on your behalf.",
    "Even in the valley of dry bones, I can speak life and cause a mighty army to rise.",
    "I am testing your heart with the 'little' so I can trust you with the 'much'.",
    "I am moving you from the back of the line to the front; favor is your accelerator.",
    "The liberal soul shall be made fat; as you pour out, I will pour back in.",
    "You are the head and not the tail; you are above only and not beneath.",
    "I am breaking the chains of addiction and the weights of depression.",
    "You will bloom even in the desert; I am making a way in the wilderness.",
    "Your children will be mighty in the land; your generation will be blessed.",
    "I have heard your silent prayers; the ones you were too tired to speak.",
    "The righteous are as bold as a lion; stop shrinking and step into your calling.",
    "I am a wall of fire around you, and I will be the glory in your midst.",
    "I am restoring your soul; leading you beside quiet waters.",
    "Death has been swallowed up in victory; the things that tried to kill you are under your feet.",
    "Every promise I have made to you is 'Yes' and 'Amen'.",
    "You are in a transition phase; don't judge the finished product by the messy middle.",
    "I am giving you favor with people you don't even know; your name is being mentioned in rooms.",
    "The trauma of the past is being washed away by the river of my presence.",
    "There is a divine glow upon your life; people will notice you are different.",
    "Those who endure to the end shall receive the crown; the finish line is near.",
    "I am shifting you from survival mode to overflow mode.",
    "I am opening the eyes of your heart to see the hope to which you are called.",
    "Blessed are the pure in heart, for they shall see God moving in their daily lives.",
    "Speak to the mountain; do not describe the mountain to Me, tell it about Me.",
    "When the world is shaking, your hope is anchored in the Unshakable Kingdom.",
    "My grace is a shield that surrounds you; it covers mistakes and empowers future.",
    "You are about to reap where you did not sow; a harvest of grace is coming.",
    "My peace I give to you; not as the world gives. Let not your heart be troubled.",
    "You are a city set on a hill; your light cannot and will not be hidden.",
    "I am taking you to a place you've never been, to show you things you've never seen.",
    "When you are weak, then you are truly strong, because my power is resting on you.",
    "I am aligning your desires with my will so that your success is guaranteed.",
    "You will be my witness to the ends of the earth; your story will go further than your feet.",
    "I am a rewarder of those who diligently seek Me.",
    "I will not leave you as orphans; I will come to you and stay with you.",
    "The Spirit I gave you does not make you timid, but gives you power, love, and discipline.",
    "You are being built into a spiritual house, a royal people.",
    "It is for freedom that Christ has set us free. Stand firm.",
    "The old has gone, the new is here! You are a new creation.",
    "The one who calls you is faithful, and He will do it.",
    "Put on the full armor of light; the darkness has no authority over you.",
    "Your final decree is this: It is finished, it is done, it is yours."
];